SELECT 
 Worker_Details.FIRST_NAME,
	Worker_Details.LAST_NAME,
       Worker_Details.DEPARTMENT
FROM Worker_Details,Title
WHERE Worker_Details.WORKER_ID = Title.WORKER_REF_ID;

WITH HIGHEST AS (
    SELECT DEPARTMENT,
	FIRST_NAME , 
	SALARY,
    DENSE_RANK() OVER(PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS RowNum
        FROM Worker_Details
)
SELECT DEPARTMENT, FIRST_NAME, SALARY
    FROM HIGHEST
    WHERE RowNum = 1;