SELECT ENAME,SAL
FROM EMP
WHERE SAL BETWEEN 500 AND 1000;

SELECT EMPNO,ENAME,SAL
FROM EMP
WHERE SAL IN (800,950,3000,5000);

SELECT ENAME
FROM EMP
WHERE ENAME LIKE '_L%';

SELECT ENAME
FROM EMP
WHERE ENAME LIKE '%D' ;